######################################################################
# Automatically generated by qmake (3.0) ven. mars 8 13:59:11 2013
######################################################################

TEMPLATE = app
TARGET = server
INCLUDEPATH += .

# Input
SOURCES += main.cpp
