import multiprocessing


buildPath = '.build'


cpuCount = multiprocessing.cpu_count()
print 'Compilation using', cpuCount, 'processors'
SetOption('num_jobs', cpuCount)


SConscript('SConscript', variant_dir=buildPath)
Clean('.', buildPath)

